[phases.setup]
nixPkgs = ["ffmpeg", "python310", "python310Packages.pip", "python310Packages.python-dotenv"]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "python music_bot.py"